# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 135)
        self.b_confirmAction = QtWidgets.QDialogButtonBox(Dialog)
        self.b_confirmAction.setGeometry(QtCore.QRect(50, 90, 341, 32))
        self.b_confirmAction.setOrientation(QtCore.Qt.Horizontal)
        self.b_confirmAction.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.b_confirmAction.setObjectName("b_confirmAction")
        self.l_warn1 = QtWidgets.QLabel(Dialog)
        self.l_warn1.setGeometry(QtCore.QRect(20, 20, 341, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.l_warn1.setFont(font)
        self.l_warn1.setObjectName("l_warn1")
        self.l_actionList = QtWidgets.QLabel(Dialog)
        self.l_actionList.setGeometry(QtCore.QRect(20, 50, 121, 16))
        self.l_actionList.setObjectName("l_actionList")
        self.c_confirm = QtWidgets.QCheckBox(Dialog)
        self.c_confirm.setGeometry(QtCore.QRect(20, 89, 151, 31))
        self.c_confirm.setObjectName("c_confirm")

        self.retranslateUi(Dialog)
        self.b_confirmAction.accepted.connect(Dialog.accept) # type: ignore
        self.b_confirmAction.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Confirm Action"))
        self.l_warn1.setText(_translate("Dialog", "You are about to execute the following action(s):"))
        self.l_actionList.setText(_translate("Dialog", "ActionList"))
        self.c_confirm.setText(_translate("Dialog", "Confirm Execution"))
