# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debug.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(508, 338)
        self.le_vc = QtWidgets.QLineEdit(Dialog)
        self.le_vc.setGeometry(QtCore.QRect(30, 260, 211, 21))
        self.le_vc.setObjectName("le_vc")
        self.le_mcb = QtWidgets.QLineEdit(Dialog)
        self.le_mcb.setGeometry(QtCore.QRect(270, 260, 211, 21))
        self.le_mcb.setObjectName("le_mcb")
        self.pt_vc = QtWidgets.QPlainTextEdit(Dialog)
        self.pt_vc.setGeometry(QtCore.QRect(30, 60, 211, 191))
        self.pt_vc.setPlainText("")
        self.pt_vc.setObjectName("pt_vc")
        self.pt_mcb = QtWidgets.QPlainTextEdit(Dialog)
        self.pt_mcb.setGeometry(QtCore.QRect(270, 60, 211, 191))
        self.pt_mcb.setObjectName("pt_mcb")
        self.l_vc = QtWidgets.QLabel(Dialog)
        self.l_vc.setGeometry(QtCore.QRect(30, 40, 81, 16))
        self.l_vc.setObjectName("l_vc")
        self.l_mcb = QtWidgets.QLabel(Dialog)
        self.l_mcb.setGeometry(QtCore.QRect(270, 40, 151, 16))
        self.l_mcb.setObjectName("l_mcb")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Debug Tools"))
        self.le_vc.setPlaceholderText(_translate("Dialog", "VC Dummy Input"))
        self.le_mcb.setPlaceholderText(_translate("Dialog", "MCB Dummy Input"))
        self.l_vc.setText(_translate("Dialog", "Valve Cart"))
        self.l_mcb.setText(_translate("Dialog", "Mission Control Board"))
