# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debug.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(820, 622)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.l_vc = QtWidgets.QLabel(Dialog)
        self.l_vc.setObjectName("l_vc")
        self.gridLayout.addWidget(self.l_vc, 0, 0, 1, 1)
        self.l_mcb = QtWidgets.QLabel(Dialog)
        self.l_mcb.setObjectName("l_mcb")
        self.gridLayout.addWidget(self.l_mcb, 0, 1, 1, 1)
        self.le_vc = QtWidgets.QLineEdit(Dialog)
        self.le_vc.setObjectName("le_vc")
        self.gridLayout.addWidget(self.le_vc, 2, 0, 1, 1)
        self.le_mcb = QtWidgets.QLineEdit(Dialog)
        self.le_mcb.setObjectName("le_mcb")
        self.gridLayout.addWidget(self.le_mcb, 2, 1, 1, 1)
        self.pt_mcb = QtWidgets.QPlainTextEdit(Dialog)
        self.pt_mcb.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pt_mcb.setReadOnly(True)
        self.pt_mcb.setObjectName("pt_mcb")
        self.gridLayout.addWidget(self.pt_mcb, 1, 1, 1, 1)
        self.pt_vc = QtWidgets.QPlainTextEdit(Dialog)
        self.pt_vc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.pt_vc.setReadOnly(True)
        self.pt_vc.setPlainText("")
        self.pt_vc.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.pt_vc.setObjectName("pt_vc")
        self.gridLayout.addWidget(self.pt_vc, 1, 0, 1, 1)
        self.c_vc_verbose = QtWidgets.QCheckBox(Dialog)
        self.c_vc_verbose.setObjectName("c_vc_verbose")
        self.gridLayout.addWidget(self.c_vc_verbose, 3, 0, 1, 1)
        self.c_mcb_verbose = QtWidgets.QCheckBox(Dialog)
        self.c_mcb_verbose.setObjectName("c_mcb_verbose")
        self.gridLayout.addWidget(self.c_mcb_verbose, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Debug Tools"))
        self.l_vc.setText(_translate("Dialog", "Valve Cart"))
        self.l_mcb.setText(_translate("Dialog", "Mission Control Board"))
        self.le_vc.setPlaceholderText(_translate("Dialog", "VC Dummy Input"))
        self.le_mcb.setPlaceholderText(_translate("Dialog", "MCB Dummy Input"))
        self.c_vc_verbose.setText(_translate("Dialog", "Verbose Logging"))
        self.c_mcb_verbose.setText(_translate("Dialog", "Verbose Logging"))
