# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PortSel.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(435, 130)
        self.b_VCPort = QtWidgets.QDialogButtonBox(Dialog)
        self.b_VCPort.setGeometry(QtCore.QRect(20, 90, 391, 32))
        self.b_VCPort.setOrientation(QtCore.Qt.Horizontal)
        self.b_VCPort.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.b_VCPort.setObjectName("b_VCPort")
        self.t_VCPort = QtWidgets.QLineEdit(Dialog)
        self.t_VCPort.setGeometry(QtCore.QRect(80, 10, 181, 21))
        self.t_VCPort.setObjectName("t_VCPort")
        self.l_VCPort = QtWidgets.QLabel(Dialog)
        self.l_VCPort.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.l_VCPort.setObjectName("l_VCPort")
        self.l_MCBPort = QtWidgets.QLabel(Dialog)
        self.l_MCBPort.setGeometry(QtCore.QRect(40, 50, 41, 16))
        self.l_MCBPort.setObjectName("l_MCBPort")
        self.t_MCBPort = QtWidgets.QLineEdit(Dialog)
        self.t_MCBPort.setGeometry(QtCore.QRect(80, 50, 181, 21))
        self.t_MCBPort.setObjectName("t_MCBPort")
        self.c_vc = QtWidgets.QComboBox(Dialog)
        self.c_vc.setGeometry(QtCore.QRect(270, 10, 151, 26))
        self.c_vc.setObjectName("c_vc")
        self.c_mcb = QtWidgets.QComboBox(Dialog)
        self.c_mcb.setGeometry(QtCore.QRect(270, 50, 151, 26))
        self.c_mcb.setObjectName("c_mcb")

        self.retranslateUi(Dialog)
        self.b_VCPort.accepted.connect(Dialog.accept) # type: ignore
        self.b_VCPort.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Valve Cart Connection"))
        self.l_VCPort.setText(_translate("Dialog", "Valve Cart"))
        self.l_MCBPort.setText(_translate("Dialog", "MCB"))
